<?php
/**
 * Created by PhpStorm.
 * User: dsh
 * Date: 2017/5/19
 * Time: 15:20
 */

namespace common\models\query;

use yii\db\ActiveQuery;

class CountQuery extends ActiveQuery
{
    public $pageSize = 10;

    public $page = 0;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->offset(null);
        $this->limit(null);
    }
}