<?php
/**
 * Created by PhpStorm.
 * User: dsh
 * Date: 2016/12/5
 * Time: 15:18
 */

namespace common\models\query;


use yii\db\ActiveQuery;

/**
 * Class ListQuery
 * @package app\models\query
 */
class ListQuery extends ActiveQuery
{
    public $pageSize = 10;

    public $page = 1;

    public $orderBy = [];

    public $filterFields = [];

    public $selectColumn = [];

    /**
     * 查询where设置别名
     * @var
     */
    public $alias;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        if (!empty($this->selectColumn)) {
            if (!empty($this->alias)) {
                foreach ($this->selectColumn as &$column) {
                    $column = $this->alias . '.' . $column;
                }
            }
            $this->select($this->selectColumn);
        }
        $this->asArray();
        $this->offset(($this->page - 1) * $this->pageSize);
        $this->limit($this->pageSize);
        if (!empty($this->orderBy)) {
            $this->orderBy($this->orderBy);
        }
    }

    /**
     * 设置表别名
     * @param $alias
     * @return $this
     */
    public function setAlias($alias)
    {
        $this->alias = $alias;
        return $this;
    }

    /**
     * 返回列表数据
     * @param null $db
     * @return array|\yii\db\ActiveRecord[]
     */
    public function listAll($db = null)
    {
        if (!empty($this->filterFields)) {
            if(!empty($this->alias))
            {
                $newFilterFields = [];
                foreach ($this->filterFields as $key => $column) {
                    $newFilterFields[$this->alias . '.' . $key] = $column;
                }
                $this->filterFields = $newFilterFields;
            }
            $this->andFilterWhere($this->filterFields);
        }
        $data = parent::all($db);
        $dataCount = count($data);
        $totalCount = ($this->page - 1) * $this->pageSize + $dataCount;
        if ($dataCount == $this->pageSize) {
            $totalCount += 1;
        }
        return [
            'count' => $totalCount,
            'data'  => $data,
        ];
    }


    /**
     * 返回列表数据 - 模糊搜索
     * @param null $db
     * @return array|\yii\db\ActiveRecord[]
     */
    public function listLikeAll($db = null)
    {
        if (!empty($this->filterFields)) {
            $where = [];
            foreach ($this->filterFields as $k=>$v){
               if($v){
                   $where[] = ['like',$k,$v];
               }
            }
            if(count($where)>=2){
                $where = ['And',$where];
            }else{
                $where = $where[0];
            }
            $this->andFilterWhere($where);
        }
        $data = parent::all($db);
        $dataCount = count($data);
        $totalCount = ($this->page - 1) * $this->pageSize + $dataCount;
        if ($dataCount == $this->pageSize) {
            $totalCount += 1;
        }
        return [
            'count' => $totalCount,
            'data'  => $data,
        ];
    }
}