server {
    listen 8097;
    server_name fastadmin.example.com;

    # 设置默认网站根目录和索引文件
    root /stock_admin/public;

    location / {
        if (!-e $request_filename) {
            rewrite ^(.*)$ /index.php?s=/$1 last;
            break;
        }
    }

    # 处理 /admin.php/ 路径下的请求
    location ^~ /admin.php/ {
        if (!-e $request_filename) {
            rewrite ^\/admin\.php(.*)$ /admin.php?s=$1 last;
            break;
        }
    }

    # 配置 PHP 处理
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }
}