version: '3.8'

services:
  frontend:
    image: ghcr.io/${GITHUB_USERNAME}/${GITHUB_REPO}/frontend:latest
    container_name: ecex-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - ecex-network

networks:
  ecex-network:
    driver: bridge

